# 1 ライブラリとデータの作成

In [1]:
import numpy as np

## 1.1 次元

In [2]:
x0 = np.array(1)
print(x0, x0.shape) # スカラー

1 ()


In [3]:
x1 = np.array([1,2,3,4])
print(x1, x1.shape) # ベクトル

[1 2 3 4] (4,)


In [4]:
x2 = np.array([[1,2],[3,4]])
print(x2, x2.shape) # 行列

[[1 2]
 [3 4]] (2, 2)


## 1.2 連続データ

In [5]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


## 1.3 ランダムデータ

In [6]:
np.random.seed(1)

In [7]:
x = np.random.rand(2, 2)
print(x)

[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]]


In [8]:
x = np.random.randn(2, 2)
print(x)

[[-0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387 ]]


## 1.4 0と1

In [9]:
x = np.zeros((3,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
x = np.ones((5,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 2 データの参照

In [11]:
x = np.random.randn(3,5)
print(x)

[[ 1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794]
 [-2.06014071 -0.3224172  -0.38405435  1.13376944 -1.09989127]
 [-0.17242821 -0.87785842  0.04221375  0.58281521 -1.10061918]]


In [12]:
print(x[0,:])

[ 1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794]


In [13]:
print(x[:,3])

[-0.24937038  1.13376944  0.58281521]


In [14]:
print(x[0:2,:])

[[ 1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794]
 [-2.06014071 -0.3224172  -0.38405435  1.13376944 -1.09989127]]


# 3 演算

In [15]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x+10,x-10,x*10,x/10) # スカラーとの四則演算
print(x+y,x-y,x+y,x/y) # ベクトル同士の四則演算
print(np.dot(x,y)) # ベクトルの内積

[11 12 13 14] [-9 -8 -7 -6] [10 20 30 40] [0.1 0.2 0.3 0.4]
[ 6  8 10 12] [-4 -4 -4 -4] [ 6  8 10 12] [0.2        0.33333333 0.42857143 0.5       ]
70


In [16]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x+10) # スカラーとの四則演算
print(x+y) # 行列同士の四則演算
print(np.dot(x,y)) # 行列の内積

[[11 12]
 [13 14]]
[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


# 4 特殊な関数

## 4.1 sumとmean

In [17]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [18]:
print(x.sum())
print(x.sum(axis=0), x.sum(axis=1))

10
[4 6] [3 7]


In [19]:
print(x.mean())
print(x.mean(axis=0), x.mean(axis=1))

2.5
[2. 3.] [1.5 3.5]


## 4.2 reshapeとtranspose

In [20]:
x = np.arange(30)
print(x.reshape(5,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [21]:
print(x.reshape(2,3,5))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [22]:
print(x.reshape(3,-1))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [23]:
y = x.reshape(2, 3, 5)
print(y.transpose(1,0,2))

[[[ 0  1  2  3  4]
  [15 16 17 18 19]]

 [[ 5  6  7  8  9]
  [20 21 22 23 24]]

 [[10 11 12 13 14]
  [25 26 27 28 29]]]
